name: Publish
on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/agentic-layer-sdk-adk
    permissions:
      id-token: write

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v5'

      - name: Install uv
        uses: 'astral-sh/setup-uv@v7'
        with:
          version: "0.9.7"
          enable-cache: true

      - name: Setup Python
        uses: 'actions/setup-python@v6'
        with:
          python-version-file: "pyproject.toml"

      - name: Install Dependencies
        working-directory: adk
        run: uv sync

      - name: uv Version Bump
        working-directory: adk
        run: |-
          VERSION=${{ github.ref_name }}
          uv version "${VERSION#v}"

      - name: 'Build adk package'
        working-directory: adk
        run: uv build

      - name: 'Publish adk package to PyPI'
        uses: pypa/gh-action-pypi-publish@release/v1
